#!/bin/bash
#################################################
#	Title:	goto-chroot			#
#        Date:	2014-06-18			#
#     Version:	1.0				#
#      Author:	baho-utot@columbus.rr.com	#
#     Options:					#
#################################################
#
#	CHROOT to ${LFS}
#	This chroot is for after mk-lfs completes
#
set -o errexit		# exit if error...insurance ;)
set -o nounset		# exit if variable not initalized
set +h			# disable hashall
source config.inc	#
source common.inc	#
source build.inc	#
PRGNAME=${0##*/}	# script name minus the path
#
#	If already in chroot then do nothing
#
[ ${EUID} -eq 0 ]	|| die "${PRGNAME}: Need to be root user: FAILURE"
[ -z "${LFS}" ]		&& die "${PRGNAME}: LFS not set: FAILURE"
[ -d "${LFS}" ]		|| die "${PRGNAME}: Already in chroot: FAILURE"
#	Mount kernel filesystem
if ! mountpoint ${LFS}/dev	>/dev/null 2>&1; then mount --bind /dev ${LFS}/dev; fi
if ! mountpoint ${LFS}/dev/pts	>/dev/null 2>&1; then mount -t devpts devpts ${LFS}/dev/pts -o gid=5,mode=620; fi
if ! mountpoint ${LFS}/proc	>/dev/null 2>&1; then mount -t proc proc ${LFS}/proc; fi
if ! mountpoint ${LFS}/sys 	>/dev/null 2>&1; then mount -t sysfs sysfs ${LFS}/sys; fi
if ! mountpoint ${LFS}/run	>/dev/null 2>&1; then mount -t tmpfs tmpfs ${LFS}/run; fi
if [ -h ${LFS}/dev/shm ];			 then mkdir -pv ${LFS}/$(readlink ${LFS}/dev/shm); fi
#	Goto chroot everthing is ready. get to building
chroot "$LFS" /usr/bin/env -i \
	HOME=/root TERM="$TERM" PS1='\u:\w\$ ' \
	PATH=/bin:/usr/bin:/sbin:/usr/sbin \
	/bin/bash --login
#	Unmount kernel filesystem
if mountpoint ${LFS}/run	>/dev/null 2>&1; then umount ${LFS}/run; fi
if mountpoint ${LFS}/sys	>/dev/null 2>&1; then umount ${LFS}/sys; fi
if mountpoint ${LFS}/proc	>/dev/null 2>&1; then umount ${LFS}/proc; fi
if mountpoint ${LFS}/dev/pts	>/dev/null 2>&1; then umount ${LFS}/dev/pts; fi
if mountpoint ${LFS}/dev	>/dev/null 2>&1; then umount ${LFS}/dev; fi
exit 0