#!/bin/bash
#################################################
#	Title:	mk-copy				#
#        Date:	2014-06-18			#
#     Version:	1.0				#
#      Author:	baho-utot@columbus.rr.com	#
#     Options:					#
#################################################
#
#	Copy build system inot ${LFS}
#
set -o errexit		# exit if error...insurance ;)
set -o nounset		# exit if variable not initalized
set +h			# disable hashall
source config.inc
source common.inc
source build.inc
PRGNAME=${0##*/}	# script name minus the path
[ ${EUID} -eq 0 ] || die "${PRGNAME}: Need to be root user: FAILURE"
LIST="BOOK BUILD BUILDROOT LOGS RPMS SOURCES SPECS "				# directories
LIST+="Overview README README.MD "						# docs
LIST+="config config-3.10.10-i686 config-3.13.3-x86_64 locale-gen.conf "	# configuration files
LIST+="macros "									# configuration files
LIST+="md5sums-lfs md5sums-rpm wget-lfs wget-rpm "				# source package data
LIST+="locale-gen.sh version-check "						# lfs scripts
LIST+="build.inc common.inc config.inc "					# build system includes
LIST+="mk-clean mk-config mk-copy mk-fetch mk-filesystem mk-lfs "		# build system scripts
LIST+="mk-master mk-mount mk-rmuser mk-tools mk-umount mk-user "		# build system scripts
msg "Install build system"
mountpoint ${LFS} > /dev/null 2>&1 || die "	/mnt/lfs is not mounted: "
cmd-line "	Installing directories" "install -vdm 755 ${LFS}/${PARENT}/{BOOK,BUILD,BUILDROOT,LOGS,RPMS,SOURCES,SPECS}"
cmd-line "	Copying files" "cp -var ${LIST} ${LFS}/${PARENT}"
cmd-line "	Setting ownership to lfs user" "chown -R lfs:lfs ${LFS}/"
exit
