#!/bin/bash
#################################################
#	Title:	mk-			#
#        Date:	2014-06-18			#
#     Version:	1.0				#
#      Author:	baho-utot@columbus.rr.com	#
#     Options:					#
#################################################
set -o errexit		# exit if error...insurance ;)
set -o nounset		# exit if variable not initalized
set +h			# disable hashall
source config.inc
source common.inc
source build.inc
PRGNAME=${0##*/}	# script name minus the path