#!/bin/bash
#################################################
#	Title:	mk-filesystem			#
#        Date:	2014-06-18			#
#     Version:	1.0				#
#      Author:	baho-utot@columbus.rr.com	#
#     Options:					#
#################################################
#
#	Creates filesystem on device using parameter set in config.inc
#
#	DEVICE		-	/dev/sdxx
#	MNT_POINT	-	/mnt/lfs
#	FILSYSTEM	-	ext4
set -o errexit		# exit if error...insurance ;)
set -o nounset		# exit if variable not initalized
set +h			# disable hashall
source config.inc
source common.inc
source build.inc
PRGNAME=${0##*/}	# script name minus the path
[ ${EUID} -eq 0 ] || die "${PRGNAME}: Need to be root user: FAILURE"
msg "Create/wipe filesystem"
msg_line "	Create/wipe filesystem on /dev/${DEVICE} (y/n) "
read p
case $p in
	y|Y)	true ;;
	n|N)	die "	Canceling create filesystem" ;;
	*)	die "	Invalid response, Can not continue" ;;
esac
[ "y" = "${p}" ] && cmd-line "	Creating filesystem on device: ${DEVICE}" "mkfs -v -t ${FILESYSTEM} /dev/${DEVICE}"
exit 0