#!/bin/bash
#################################################
#	Title:	mk-master			#
#        Date:	2014-06-18			#
#     Version:	1.0				#
#      Author:	baho-utot@columbus.rr.com	#
#     Options:					#
#	     : Build the lfs system		#
#	     : Master script			#
#################################################
set -o errexit						# exit if error...insurance ;)
set -o nounset						# exit if variable not initalized
set +h
source config.inc
PRGNAME=${0##*/}	# script name minus the path
> ${LOGFILE}
./mk-fetch						# retrieve all the source packages required
sudo ./mk-filesystem					# create filesystem on device
sudo  ./mk-mount					# mount device onto /mnt/lfs
sudo ./mk-user						# create lfs user on host system
sudo ./mk-copy						# copy build system to /mnt/lfs
sudo su - lfs -c "${LFS}${PARENT}/mk-tools"		# build the tools chain
#sudo ./mk-lfs						# build lfs system into /mnt/lfs (mount kernel filesystem,chroot and build )
#su -c ./mk-config					# configure built system
sudo ./mk-umount					# unmount /mnt/lfs
sudo ./mk-rmuser					# remove lfs user from host

#su -c ./'mk-clean'					# restore host system





