#!/bin/bash
#################################################
#	Title:	mk-rmuser			#
#        Date:	2014-05-31			#
#     Version:	1.0				#
#      Author:	baho-utot@columbus.rr.com	#
#     Options:					#
#################################################
#
#	Remove lfs user on host
#
set -o errexit		# exit if error...insurance ;)
set -o nounset		# exit if variable not initalized
set +h			# disable hashall
source config.inc
source common.inc
source build.inc
PRGNAME=${0##*/}	# script name minus the path
[ ${EUID} -eq 0 ] || die "${PRGNAME}: Need to be root user: FAILURE"
msg "Removing lfs user"
getent passwd lfs > /dev/null 2>&1 && cmd-line "	Removing lfs user" "userdel  lfs"
getent group  lfs > /dev/null 2>&1 && cmd-line "	Removing lfs group" "groupdel lfs"
[ -d "/home/lfs" ] && cmd-line "	Removing home directory" "rm -vrf \"/home/lfs\""
exit 0

