#!/bin/bash
#################################################
#	Title:	mk-user				#
#        Date:	2014-05-31			#
#     Version:	1.0				#
#      Author:	baho-utot@columbus.rr.com	#
#     Options:					#
#################################################
#
#	Create lfs user on host
#
set -o errexit		# exit if error...insurance ;)
set -o nounset		# exit if variable not initalized
set +h			# disable hashall
source config.inc
source common.inc
source build.inc
PRGNAME=${0##*/}	# script name minus the path
[ ${EUID} -eq 0 ] || die "${PRGNAME}: Need to be root user: FAILURE"
[ -d /home/lfs ] || {
	msg "Creating lfs user"
	getent group  lfs > /dev/null 2>&1 || cmd-line "	Creating lfs group" "groupadd lfs"
	getent passwd lfs > /dev/null 2>&1 || cmd-line "	Creating lfs user" "useradd -c 'LFS user' -g lfs -m -k /dev/null -s /bin/bash lfs"
	cmd-line "	Adding password to lfs" "passwd -l lfs"
	cat > /home/lfs/.bash_profile <<- "EOF"
		exec env -i HOME=/home/lfs TERM=${TERM} PS1='\u:\w\$ ' /bin/bash
	EOF
	cat > /home/lfs/.bashrc <<- "EOF"
		set +h
		umask 022
		LFS=/mnt/lfs
		LC_ALL=POSIX
		LFS_TGT=$(uname -m)-lfs-linux-gnu
		PATH=/tools/bin:/bin:/usr/bin
		export LFS LC_ALL LFS_TGT PATH
	EOF
	cmd-line "	Changing ownership /home/lfs" "chown -R lfs:lfs /home/lfs"
}
exit 0