#!/bin/bash
#################################################
#	Title:	mk-			#
#        Date:	2014-06-18			#
#     Version:	1.0				#
#      Author:	baho-utot@columbus.rr.com	#
#     Options:					#
#################################################
set -o errexit		# exit if error...insurance ;)
set -o nounset		# exit if variable not initalized
set +h			# disable hashall
source config.inc
source common.inc
source build.inc
PRGNAME=${0##*/}	# script name minus the path
[ ${EUID} -eq 0 ] || die "${PRGNAME}: Need to be root user: FAILURE"
msg "Unmounting ${LFS} partition"
mountpoint ${LFS} > /dev/null 2>&1 && {
	cmd-line "	Unmounting ${LFS}" "umount -v -R ${LFS}"
	cmd-line "	Removing ${LFS} directory" "rm -vrf ${LFS}"
	cmd-line "	Removing symlink /tools" "rm -vrf /tools"
}
exit 0
